version: "3"
services:
  voidimp-strapi:
    container_name: voidimp-strapi
    build: .
    image: voidimp-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: voidimp-postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    links:
      - voidimp-postgres:voidimp-postgres
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - voidimp-cms-pdv:/opt/app/public
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - voidimp-postgres

  voidimp-postgres:
    image: postgres:12.0-alpine
    container_name: voidimp-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - voidimp-cms-ddv:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi

  voidimp-nginx:
    image: nginx:1.15-alpine
    container_name: voidimp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/ssl:/ssl/

networks:
  strapi:
    name: Strapi
    driver: bridge

volumes:
  voidimp-cms-pdv:
    external: true
  voidimp-cms-ddv:
    external: true
